language: node_js
node_js: '8'
services:
- postgresql
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: kuHRruJ7XB9ITUfaC835pxF9y57FbABaK5kYqNhLUQ43tVkF+MpFpUzfydH6VPz56f2mH6U2yn+HOQfxpyiC1DXbl+qUczu+HnKx2HTzJ6QbbLPZtx4owFZZoMSgxN7oS/SgMyoE7zPoX4HEPe8AAUYfZlxt7GrVJNrr2PB746QO02uS+hQGhGntZMrQIQlSmk6m6nLaq2TvzQuYvvCkTEm9PifXudR7OzuWSTuOBV1imxlEzSEkC1QhF136uiY97/U3GtKbADfawiaSAXnY8KfuAyZc5OwILxqYvHYybZHGmtDYN02+2jcySyk5XAOnEoWEEmlyTUbeaQObCCN7w/5dTE3KEjPCXkib2zjz/Wv5T184FqwWtzQFPD4eptDxBOMCG9kHXVm3Qi4rSd9VE9u1CSMP8Z8xyGu/Auw1dbZOI8ZpvEtDE/EOoWY4UMcbSOMMyBPb4DqL7fSe8oARtCefIpwv50TAY1zQbCuZ0d5xdSgwS2CCHsr1JUIADhKOhsi8sQf8xokoSmg31SziGg6eXeQExZN9AeOplXNJirifKG8PIljZCHuPXL2vc6WkUIoaab/rJRNWwnOr+VDHf5qqvMYFoFB5PmN2g+fiPozzABitWjm96seaCQZgcPIQgc2mi37DW5qJpX9zrNPXN7/4bfmlo4UyLCK5kOo45oo=
